DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR,
    last_name VARCHAR,
    surname VARCHAR,
    message VARCHAR(250),
    start_time DATE,
    end_time DATE,
    start_day DATE,
    end_day DATE
    );